# Generated by Django 4.1.1 on 2022-11-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='points',
        ),
    ]
