# Generated by Django 4.1.1 on 2022-11-28 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_counter_remove_choice_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.choice'),
        ),
    ]
